name: Tests (End-to-End)

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v3
        env:
          BASIQ_API_KEY: ${{ secrets.BASIQ_API_KEY }}
        with:
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
